eureka:
  client:
    serviceUrl:
      defaultZone: http://47.96.89.227:18761/eureka/
server:
  port: 18764
spring:
  application:
    name: service-elk
  zipkin:
    base-url: http://47.96.89.227:9411
  sleuth:
    sampler:
#      percentage: 1.0
      probability: 1.0
logging:
  config: classpath:logback.xml


